spring:
  application:
    name: sleuth-provide
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    trace-id128: true
  zipkin:
    base-url: http://zipkin:9411/ # 指定了 Zipkin 服务器的地址
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'
#  logging.level.org.springframework.web=DEBUG


